-- CREATE TABLE `keycloak`.`COMPANY` ( `ID` VARCHAR(36) NOT NULL, `NAME` VARCHAR(255) NOT NULL, `REALM_ID` VARCHAR(36) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=INNODB CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `prospecting_user_entity` (
  `ID` varchar(36) COLLATE utf8_unicode_ci NOT NULL,
  `EMAIL` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `REALM_ID` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CREATED_TIMESTAMP` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci



