DROP TABLE IF EXISTS prospecting_user_entity;

CREATE TABLE `prospecting_user_entity` (
  `ID` VARCHAR(36) COLLATE utf8_unicode_ci NOT NULL,
  `EMAIL` VARCHAR(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `REALM_ID` VARCHAR(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CREATED_TIMESTAMP` BIGINT(20) DEFAULT NULL,
  `STATUS` VARCHAR(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE(`EMAIL`, `REALM_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;





